### ISSUE TITLE
Compose migration

### ISSUE THREAD

**Issue by CriticalGnome** [CriticalGnome/CleanArchitectureDemo#33]
**Problem**
XML-layouts are no more fully supported

**Solution**
Migrate screens to Jetpack Compose

**Comment by itsPronay** [comment]
can I help with the migration? I have a little experience with compose @CriticalGnome

**Comment by CriticalGnome** [comment]
This repository contains only a skeleton based on Clean Architecture layers. It only has one sample activity, just to be able to run. I don't see any difficulty in adding additional activities in any way you want (view-based or compose-based).
